/**
 * The accessible component set.
 *
 * Written directly rather than generated by the shadcn CLI (ADR-004): same
 * conventions — Tailwind, a `cn()` merger, variant props — but no network-
 * dependent generator step and no runtime dependency we do not need.
 *
 * Accessibility is owned here, so it is deliberate rather than inherited:
 * every input is label-associated, errors are wired with `aria-describedby`
 * and `aria-invalid`, and status messages announce through live regions.
 */

import * as React from 'react';

export function cn(...classes: (string | false | null | undefined)[]): string {
  return classes.filter(Boolean).join(' ');
}

// --------------------------------------------------------------------------
// Button
// --------------------------------------------------------------------------

type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';
type ButtonSize = 'sm' | 'md' | 'lg';

const BUTTON_VARIANTS: Record<ButtonVariant, string> = {
  primary: 'bg-ink text-surface hover:bg-ink-soft disabled:bg-muted',
  secondary: 'bg-surface text-ink border border-line hover:bg-surface-alt disabled:text-muted',
  ghost: 'bg-transparent text-ink hover:bg-surface-alt disabled:text-muted',
  danger: 'bg-danger text-surface hover:opacity-90 disabled:bg-muted',
};

const BUTTON_SIZES: Record<ButtonSize, string> = {
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
};

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
}

export function Button({
  variant = 'primary',
  size = 'md',
  loading = false,
  className,
  children,
  disabled,
  ...props
}: ButtonProps) {
  return (
    <button
      {...props}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      className={cn(
        'inline-flex items-center justify-center gap-2 rounded-md font-semibold transition-colors',
        'disabled:cursor-not-allowed',
        BUTTON_VARIANTS[variant],
        BUTTON_SIZES[size],
        className,
      )}
    >
      {loading && <Spinner />}
      {children}
    </button>
  );
}

function Spinner() {
  return (
    <span
      aria-hidden="true"
      className="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-t-transparent"
    />
  );
}

// --------------------------------------------------------------------------
// Field — label, hint, error, and the aria wiring that connects them
// --------------------------------------------------------------------------

export interface FieldProps {
  id: string;
  label: string;
  hint?: string;
  error?: string;
  required?: boolean;
  children: (aria: {
    id: string;
    'aria-describedby': string | undefined;
    'aria-invalid': boolean | undefined;
    'aria-required': boolean | undefined;
  }) => React.ReactNode;
}

export function Field({ id, label, hint, error, required, children }: FieldProps) {
  const hintId = hint ? `${id}-hint` : undefined;
  const errorId = error ? `${id}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;

  return (
    <div className="space-y-1.5">
      <label htmlFor={id} className="block text-sm font-semibold text-ink">
        {label}
        {required && (
          <span className="ml-1 text-danger" aria-hidden="true">
            *
          </span>
        )}
        {required && <span className="sr-only"> (required)</span>}
      </label>
      {hint && (
        <p id={hintId} className="text-sm text-muted">
          {hint}
        </p>
      )}
      {children({
        id,
        'aria-describedby': describedBy,
        'aria-invalid': error ? true : undefined,
        'aria-required': required || undefined,
      })}
      {error && (
        <p id={errorId} className="text-sm font-medium text-danger">
          {error}
        </p>
      )}
    </div>
  );
}

const CONTROL_BASE =
  'w-full rounded-md border bg-surface px-3 py-2 text-base text-ink placeholder:text-muted ' +
  'disabled:cursor-not-allowed disabled:bg-surface-alt disabled:text-muted';

export const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  function Input({ className, ...props }, ref) {
    return (
      <input
        ref={ref}
        {...props}
        className={cn(CONTROL_BASE, props['aria-invalid'] ? 'border-danger' : 'border-line', className)}
      />
    );
  },
);

export const Textarea = React.forwardRef<
  HTMLTextAreaElement,
  React.TextareaHTMLAttributes<HTMLTextAreaElement>
>(function Textarea({ className, rows = 4, ...props }, ref) {
  return (
    <textarea
      ref={ref}
      rows={rows}
      {...props}
      className={cn(
        CONTROL_BASE,
        'resize-y',
        props['aria-invalid'] ? 'border-danger' : 'border-line',
        className,
      )}
    />
  );
});

export const Select = React.forwardRef<
  HTMLSelectElement,
  React.SelectHTMLAttributes<HTMLSelectElement>
>(function Select({ className, children, ...props }, ref) {
  return (
    <select
      ref={ref}
      {...props}
      className={cn(CONTROL_BASE, props['aria-invalid'] ? 'border-danger' : 'border-line', className)}
    >
      {children}
    </select>
  );
});

export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
  label: React.ReactNode;
  description?: string;
}

export function Checkbox({ label, description, id, className, ...props }: CheckboxProps) {
  const descriptionId = description ? `${id}-description` : undefined;
  return (
    <div className={cn('flex gap-3', className)}>
      <input
        type="checkbox"
        id={id}
        aria-describedby={descriptionId}
        {...props}
        className="mt-1 h-5 w-5 shrink-0 rounded border-2 border-line accent-brand"
      />
      <div className="space-y-0.5">
        <label htmlFor={id} className="block text-sm text-ink">
          {label}
        </label>
        {description && (
          <p id={descriptionId} className="text-sm text-muted">
            {description}
          </p>
        )}
      </div>
    </div>
  );
}

// --------------------------------------------------------------------------
// Surfaces
// --------------------------------------------------------------------------

export function Card({
  children,
  className,
  as: Component = 'div',
}: {
  children: React.ReactNode;
  className?: string;
  as?: React.ElementType;
}) {
  return (
    <Component className={cn('rounded-lg border border-line bg-surface p-5', className)}>
      {children}
    </Component>
  );
}

export function CardHeader({
  title,
  description,
  actions,
  level = 2,
}: {
  title: React.ReactNode;
  description?: React.ReactNode;
  actions?: React.ReactNode;
  level?: 2 | 3 | 4;
}) {
  const Heading = `h${level}` as const;
  return (
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
      <div>
        <Heading className="text-lg font-bold text-ink">{title}</Heading>
        {description && <p className="mt-1 text-sm text-muted">{description}</p>}
      </div>
      {actions && <div className="flex shrink-0 gap-2">{actions}</div>}
    </div>
  );
}

type BadgeTone = 'neutral' | 'success' | 'warning' | 'danger' | 'info' | 'brand';

const BADGE_TONES: Record<BadgeTone, string> = {
  neutral: 'bg-surface-alt text-ink border-line',
  success: 'bg-brand-tint text-brand-deep border-brand',
  warning: 'bg-warning-tint text-warning border-warning',
  danger: 'bg-danger-tint text-danger border-danger',
  info: 'bg-info-tint text-info border-info',
  brand: 'bg-ink text-surface border-ink',
};

export function Badge({
  children,
  tone = 'neutral',
  className,
}: {
  children: React.ReactNode;
  tone?: BadgeTone;
  className?: string;
}) {
  return (
    <span
      className={cn(
        'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold',
        BADGE_TONES[tone],
        className,
      )}
    >
      {children}
    </span>
  );
}

type AlertTone = 'info' | 'warning' | 'danger' | 'success';

const ALERT_TONES: Record<AlertTone, string> = {
  info: 'border-info bg-info-tint text-info',
  warning: 'border-warning bg-warning-tint text-warning',
  danger: 'border-danger bg-danger-tint text-danger',
  success: 'border-brand bg-brand-tint text-brand-deep',
};

export function Alert({
  tone = 'info',
  title,
  children,
  className,
}: {
  tone?: AlertTone;
  title?: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      // Errors interrupt; everything else waits for a pause in speech.
      role={tone === 'danger' ? 'alert' : 'status'}
      className={cn('rounded-md border-l-4 p-4', ALERT_TONES[tone], className)}
    >
      {title && <p className="font-bold">{title}</p>}
      <div className={cn('text-sm', title && 'mt-1')}>{children}</div>
    </div>
  );
}

// --------------------------------------------------------------------------
// Table
// --------------------------------------------------------------------------

export function Table({ children, caption }: { children: React.ReactNode; caption?: string }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full border-collapse text-sm">
        {caption && <caption className="sr-only">{caption}</caption>}
        {children}
      </table>
    </div>
  );
}

export function Th({
  children,
  className,
  scope = 'col',
}: {
  children: React.ReactNode;
  className?: string;
  scope?: 'col' | 'row';
}) {
  return (
    <th
      scope={scope}
      className={cn('border-b-2 border-line px-3 py-2 text-left font-bold text-ink', className)}
    >
      {children}
    </th>
  );
}

export function Td({ children, className }: { children: React.ReactNode; className?: string }) {
  return <td className={cn('border-b border-line px-3 py-2 align-top', className)}>{children}</td>;
}

// --------------------------------------------------------------------------
// Progress and stepper
// --------------------------------------------------------------------------

export function Progress({ value, max = 100, label }: { value: number; max?: number; label: string }) {
  const percent = Math.round((value / max) * 100);
  return (
    <div className="space-y-1">
      <div className="flex justify-between text-sm">
        <span className="font-medium text-ink">{label}</span>
        <span className="text-muted">{percent}%</span>
      </div>
      <div
        role="progressbar"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={max}
        aria-label={label}
        className="h-2 w-full overflow-hidden rounded-full bg-surface-alt"
      >
        <div className="h-full bg-brand transition-[width]" style={{ width: `${percent}%` }} />
      </div>
    </div>
  );
}

export interface StepperStep {
  key: string;
  label: string;
  complete: boolean;
}

export function Stepper({
  steps,
  currentKey,
  onSelect,
}: {
  steps: StepperStep[];
  currentKey: string;
  onSelect: (key: string) => void;
}) {
  return (
    <nav aria-label="Submission steps">
      <ol className="flex flex-wrap gap-2">
        {steps.map((step, index) => {
          const isCurrent = step.key === currentKey;
          return (
            <li key={step.key}>
              <button
                type="button"
                onClick={() => onSelect(step.key)}
                aria-current={isCurrent ? 'step' : undefined}
                className={cn(
                  'flex items-center gap-2 rounded-md border px-3 py-2 text-sm font-medium transition-colors',
                  isCurrent
                    ? 'border-ink bg-ink text-surface'
                    : 'border-line bg-surface text-ink hover:bg-surface-alt',
                )}
              >
                <span
                  aria-hidden="true"
                  className={cn(
                    'flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold',
                    step.complete
                      ? 'bg-brand text-surface'
                      : isCurrent
                        ? 'bg-surface text-ink'
                        : 'bg-surface-alt text-muted',
                  )}
                >
                  {step.complete ? '✓' : index + 1}
                </span>
                {step.label}
                <span className="sr-only">{step.complete ? ' — complete' : ' — incomplete'}</span>
              </button>
            </li>
          );
        })}
      </ol>
    </nav>
  );
}

// --------------------------------------------------------------------------
// Tabs — WAI-ARIA tabs pattern with roving tabindex
// --------------------------------------------------------------------------

export interface TabItem {
  key: string;
  label: string;
  badge?: React.ReactNode;
}

export function Tabs({
  tabs,
  activeKey,
  onChange,
  children,
}: {
  tabs: TabItem[];
  activeKey: string;
  onChange: (key: string) => void;
  children: React.ReactNode;
}) {
  const refs = React.useRef<Record<string, HTMLButtonElement | null>>({});

  const onKeyDown = (event: React.KeyboardEvent) => {
    const index = tabs.findIndex((t) => t.key === activeKey);
    let next = index;
    if (event.key === 'ArrowRight') next = (index + 1) % tabs.length;
    else if (event.key === 'ArrowLeft') next = (index - 1 + tabs.length) % tabs.length;
    else if (event.key === 'Home') next = 0;
    else if (event.key === 'End') next = tabs.length - 1;
    else return;

    event.preventDefault();
    const target = tabs[next];
    if (!target) return;
    onChange(target.key);
    refs.current[target.key]?.focus();
  };

  return (
    <div>
      <div role="tablist" onKeyDown={onKeyDown} className="flex flex-wrap gap-1 border-b border-line">
        {tabs.map((tab) => {
          const selected = tab.key === activeKey;
          return (
            <button
              key={tab.key}
              ref={(el) => {
                refs.current[tab.key] = el;
              }}
              role="tab"
              type="button"
              id={`tab-${tab.key}`}
              aria-selected={selected}
              aria-controls={`panel-${tab.key}`}
              // Roving tabindex: only the active tab is in the tab order.
              tabIndex={selected ? 0 : -1}
              onClick={() => onChange(tab.key)}
              className={cn(
                'flex items-center gap-2 border-b-2 px-3 py-2 text-sm font-medium transition-colors',
                selected
                  ? 'border-ink text-ink'
                  : 'border-transparent text-muted hover:border-line hover:text-ink',
              )}
            >
              {tab.label}
              {tab.badge}
            </button>
          );
        })}
      </div>
      <div role="tabpanel" id={`panel-${activeKey}`} aria-labelledby={`tab-${activeKey}`} tabIndex={0} className="pt-5">
        {children}
      </div>
    </div>
  );
}

// --------------------------------------------------------------------------
// Empty state
// --------------------------------------------------------------------------

export function EmptyState({
  title,
  description,
  action,
}: {
  title: string;
  description?: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="rounded-lg border border-dashed border-line p-8 text-center">
      <p className="font-semibold text-ink">{title}</p>
      {description && <p className="mx-auto mt-1 max-w-prose text-sm text-muted">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

export function DescriptionList({
  items,
}: {
  items: { term: string; description: React.ReactNode }[];
}) {
  return (
    <dl className="grid gap-x-6 gap-y-3 sm:grid-cols-[minmax(9rem,auto)_1fr]">
      {items.map((item) => (
        <React.Fragment key={item.term}>
          <dt className="text-sm font-semibold text-muted">{item.term}</dt>
          <dd className="text-sm text-ink">{item.description}</dd>
        </React.Fragment>
      ))}
    </dl>
  );
}
