/**
 * The test-action DSL.
 *
 * This is the containment boundary for the entire assessment pipeline. Test
 * plans are generated by a model that reads participant-controlled content, so
 * a plan must be treated as untrusted output.
 *
 * The defence is that a plan is DATA, never code:
 *
 *   - a closed union of sixteen actions, with no `evaluate` member;
 *   - no action can express a shell command, a file:// read, or arbitrary JS;
 *   - navigation targets are re-validated against the SSRF guard at execution;
 *   - values written into a product are constrained and prefixed;
 *   - the executor is a handler map with no default case, so an unknown action
 *     is a type error at build time and a rejected step at runtime.
 *
 * A model that is successfully prompt-injected can, at worst, produce a plan
 * that fails validation. See ADR-007.
 */

import { z } from 'zod';

/** Every value the judge writes into a participant product carries this prefix. */
export const TEST_DATA_PREFIX = 'OUTSKILL-JUDGE-';

export const TEST_ACTIONS = [
  'navigate',
  'click',
  'fill',
  'select',
  'press',
  'wait',
  'assertText',
  'assertUrl',
  'assertElement',
  'screenshot',
  'reload',
  'checkPersistence',
  'checkConsole',
  'checkNetwork',
  'a11yScan',
  'cleanup',
] as const;

export type TestActionKind = (typeof TEST_ACTIONS)[number];

/**
 * Keyboard keys the judge may press.
 *
 * Restricted to navigation and submission keys. Chords that could reach browser
 * or OS functionality are absent from the union, so they cannot be requested.
 */
export const ALLOWED_KEYS = [
  'Enter',
  'Tab',
  'Shift+Tab',
  'Escape',
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'Space',
  'Backspace',
] as const;
export type AllowedKey = (typeof ALLOWED_KEYS)[number];

/**
 * Element targeting.
 *
 * Elements are addressed by accessible role and name, or by visible text /
 * label / placeholder / test id. There is no raw CSS or XPath member: selectors
 * from untrusted content should not be able to reach arbitrary DOM, and role
 * targeting also means the judge exercises the product the way a real assistive
 * technology user would.
 */
export const targetSchema = z
  .object({
    role: z
      .enum([
        'button',
        'link',
        'textbox',
        'checkbox',
        'radio',
        'combobox',
        'listbox',
        'option',
        'heading',
        'tab',
        'menuitem',
        'switch',
        'searchbox',
        'slider',
        'spinbutton',
        'dialog',
        'alert',
        'status',
        'img',
        'list',
        'listitem',
        'table',
        'row',
        'cell',
        'form',
        'navigation',
        'main',
        'region',
      ])
      .optional(),
    /** Accessible name, visible text, label, or placeholder. */
    name: z.string().min(1).max(200).optional(),
    label: z.string().min(1).max(200).optional(),
    placeholder: z.string().min(1).max(200).optional(),
    testId: z.string().min(1).max(120).optional(),
    /** Disambiguates when several elements match. */
    nth: z.number().int().min(0).max(50).optional(),
    exact: z.boolean().optional(),
  })
  .refine(
    (t) => Boolean(t.role ?? t.name ?? t.label ?? t.placeholder ?? t.testId),
    'A target must specify at least one of: role, name, label, placeholder, testId.',
  );

export type TestTarget = z.infer<typeof targetSchema>;

const baseStep = {
  /** Why this step exists — surfaced to admins reviewing the plan. */
  rationale: z.string().max(400).optional(),
  /** Cleanup steps run in a best-effort pass and never fail the run. */
  isCleanup: z.boolean().optional(),
  /** Per-step timeout, bounded so one step cannot consume the whole budget. */
  timeoutMs: z.number().int().min(100).max(60_000).optional(),
  /** A soft step records a failure as evidence without aborting the run. */
  optional: z.boolean().optional(),
};

/**
 * Values written into products.
 *
 * Constrained to a conservative character set and required to carry the judge
 * prefix on free-text fields, so anything the judge creates is identifiable and
 * removable. Structured values (emails, dates, numbers) are allowed unprefixed
 * because a product will reject a prefixed email — but they are still generated
 * by us, never taken from participant content.
 */
export const fillValueSchema = z
  .string()
  .max(500)
  .refine((v) => !/[<>{}\\`$]/.test(v), 'Fill values may not contain markup or shell metacharacters.');

export const testStepSchema = z.discriminatedUnion('action', [
  z.object({
    action: z.literal('navigate'),
    /** Validated again against the SSRF guard immediately before navigation. */
    url: z.string().url().max(2000),
    ...baseStep,
  }),
  z.object({ action: z.literal('click'), target: targetSchema, ...baseStep }),
  z.object({
    action: z.literal('fill'),
    target: targetSchema,
    value: fillValueSchema,
    ...baseStep,
  }),
  z.object({
    action: z.literal('select'),
    target: targetSchema,
    value: z.string().max(200),
    ...baseStep,
  }),
  z.object({ action: z.literal('press'), key: z.enum(ALLOWED_KEYS), ...baseStep }),
  z.object({
    action: z.literal('wait'),
    /** Bounded: a plan cannot burn the budget by waiting. */
    ms: z.number().int().min(100).max(15_000).optional(),
    target: targetSchema.optional(),
    ...baseStep,
  }),
  z.object({
    action: z.literal('assertText'),
    text: z.string().min(1).max(500),
    shouldExist: z.boolean().default(true),
    ...baseStep,
  }),
  z.object({
    action: z.literal('assertUrl'),
    contains: z.string().min(1).max(500),
    ...baseStep,
  }),
  z.object({
    action: z.literal('assertElement'),
    target: targetSchema,
    shouldExist: z.boolean().default(true),
    ...baseStep,
  }),
  z.object({ action: z.literal('screenshot'), label: z.string().max(120), ...baseStep }),
  z.object({ action: z.literal('reload'), ...baseStep }),
  z.object({
    action: z.literal('checkPersistence'),
    /** Text that must survive a reload — this is how "does data persist" is proven. */
    expectText: z.string().min(1).max(500),
    ...baseStep,
  }),
  z.object({ action: z.literal('checkConsole'), ...baseStep }),
  z.object({ action: z.literal('checkNetwork'), ...baseStep }),
  z.object({ action: z.literal('a11yScan'), label: z.string().max(120).optional(), ...baseStep }),
  z.object({ action: z.literal('cleanup'), target: targetSchema.optional(), ...baseStep }),
]);

export type TestStep = z.infer<typeof testStepSchema>;

export const MAX_PLAN_STEPS = 80;

export const testPlanSchema = z.object({
  steps: z.array(testStepSchema).min(1).max(MAX_PLAN_STEPS),
  /** Plan-level notes for the admin reviewing what was tested. */
  summary: z.string().max(1000).optional(),
});

export type GeneratedTestPlan = z.infer<typeof testPlanSchema>;

export interface PlanValidationResult {
  steps: TestStep[];
  rejected: RejectedStep[];
}

export interface RejectedStep {
  index: number;
  reason: string;
  /** The raw value, stringified and truncated, for admin review. */
  raw: string;
}

/**
 * Validate a generated plan step by step.
 *
 * Invalid steps are dropped with a recorded reason rather than failing the whole
 * plan — one malformed step should not cost a team their entire assessment, and
 * the rejection list is shown to admins so a systematically broken generator is
 * visible rather than silent.
 */
export function validatePlanSteps(raw: unknown): PlanValidationResult {
  const steps: TestStep[] = [];
  const rejected: RejectedStep[] = [];

  if (!Array.isArray(raw)) {
    return { steps, rejected: [{ index: -1, reason: 'Plan is not an array of steps.', raw: truncate(raw) }] };
  }

  raw.forEach((candidate, index) => {
    if (steps.length >= MAX_PLAN_STEPS) {
      rejected.push({ index, reason: `Plan exceeds the ${MAX_PLAN_STEPS}-step limit.`, raw: truncate(candidate) });
      return;
    }
    const parsed = testStepSchema.safeParse(candidate);
    if (parsed.success) {
      steps.push(parsed.data);
    } else {
      rejected.push({
        index,
        reason: parsed.error.issues.map((i) => `${i.path.join('.') || 'step'}: ${i.message}`).join('; '),
        raw: truncate(candidate),
      });
    }
  });

  return { steps, rejected };
}

function truncate(value: unknown, max = 300): string {
  let text: string;
  try {
    text = typeof value === 'string' ? value : JSON.stringify(value);
  } catch {
    text = String(value);
  }
  text ??= String(value);
  return text.length > max ? `${text.slice(0, max)}…` : text;
}

// --------------------------------------------------------------------------
// Safe test-data generation
// --------------------------------------------------------------------------

/**
 * Generate values the judge writes into products.
 *
 * Deterministic given a seed, so a rerun produces the same data and cleanup can
 * find what a previous run created.
 */
export function makeTestValue(kind: TestValueKind, seed: string): string {
  const suffix = shortHash(seed);
  switch (kind) {
    case 'text':
      return `${TEST_DATA_PREFIX}${suffix}`;
    case 'title':
      return `${TEST_DATA_PREFIX}Item ${suffix}`;
    case 'longText':
      return `${TEST_DATA_PREFIX}${suffix} — automated assessment entry, safe to delete.`;
    case 'email':
      return `judge.${suffix.toLowerCase()}@outskill-judge.invalid`;
    case 'number':
      return String(100 + (parseInt(suffix, 36) % 900));
    case 'date':
      // Fixed forward date — never "today", so runs stay reproducible.
      return '2030-06-15';
    case 'time':
      return '10:30';
    case 'url':
      return 'https://example.com';
    default: {
      const exhaustive: never = kind;
      throw new Error(`Unhandled test value kind: ${String(exhaustive)}`);
    }
  }
}

export type TestValueKind =
  | 'text'
  | 'title'
  | 'longText'
  | 'email'
  | 'number'
  | 'date'
  | 'time'
  | 'url';

/** Small deterministic hash — identification, not security. */
function shortHash(input: string): string {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(36).toUpperCase().padStart(6, '0').slice(0, 6);
}

/** True when a string was created by the judge — used to scope cleanup. */
export function isJudgeCreatedValue(value: string): boolean {
  return value.includes(TEST_DATA_PREFIX);
}
